apiVersion: apps/v1
kind: Deployment
metadata:
  name: wefd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wefd
  template:
    metadata:
      labels:
        app: wefd
    spec:
      containers:
      - image: okteto.dev/wefd:latest
        name: wefd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e87def9e-38d2-4b14-b4ca-f2165c7ae2db"
        - name: Vless_Path
          value: "/vlray1"
        - name: Vmess_UUID
          value: "e87def9e-38d2-4b14-b4ca-f2165c7ae2db"
        - name: Vmess_Path
          value: "/vmray2"
        - name: Share_Path
          value: "/v2link"
